Cofinity-X/cofinity-x-ba-traceability-foss

frontend/src/app/modules/page/alerts/presentation/alerts.component.spec.ts, frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html, frontend/src/app/modules/page/dashboard/presentation/dashboard.component.ts, frontend/src/app/modules/shared/components/table/table.component.html, frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.ts
Added options buttons back to menu
=> [DO-3577] Added options buttons back to menu

frontend/src/app/mocks/services/parts-mock/partsAsPlanned/partsAsPlanned.model.ts, frontend/src/app/modules/page/parts/presentation/parts.component.ts
fix: redone some local mock data to work in the tables
chore: added the missing code to enable sorting on all columns.
=> [DO-1533] Sorting of the my parts page.

frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, frontend/src/app/modules/shared/components/parts-table/parts-table.component.scss
Changed the alert symbol to an exclamation sign in the tables
=> [DO-1499] Alert symbol fix

frontend/src/app/modules/shared/components/request-notification/request-alert.component.ts, frontend/src/app/modules/shared/components/request-notification/request-notification.base.html
Set the default value for the severity select to Minor
Set the cancel button to close the dialog
=> fix: [DO-1256][patch] Small changes to fit acceptance criteria

frontend/src/app/modules/core/layout/footer/footer.component.html, frontend/src/app/modules/core/layout/header/user-navigation/user-menu.component.html, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
chore: Modified the footer to hide the FAQ and version updates page. 
chore: added the external link for imprint in both languages to the Cofinity-X imprint.
=> [DO-4464][DO-3613][minor] footer link modification

frontend/src/app/modules/page/dashboard/abstraction/dashboard.facade.ts
=> feature: added the filtering to the dashboard.

frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, frontend/src/app/modules/shared/components/parts-table/parts-table.component.scss, frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, frontend/src/app/modules/shared/components/table/table.component.html, frontend/src/app/modules/shared/components/table/table.component.scss
=> DO-4596 add floating config and menu on tables

frontend/src/app/modules/page/other-parts/presentation/other-parts.component.scss, frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.html, frontend/src/app/modules/page/parts/presentation/parts.component.html, frontend/src/app/modules/page/parts/presentation/parts.component.scss, frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.html, frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.ts, frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.html, frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.scss, frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.spec.ts, frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.ts
Implementation of Investigation for component
=> [DO-4769] Investigation for component

frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, frontend/src/app/modules/shared/components/request-notification/request-alert.component.ts, frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts, frontend/src/app/modules/shared/components/request-notification/request-notification.base.html, frontend/src/app/modules/shared/components/request-notification/request-notification.base.spec.ts, frontend/src/app/modules/shared/components/request-notification/request-notification.base.ts
Enabled Submit button in create alert/investigation dialogs with validation
Fixed pressing enter activating cancel button
Changed severity select to no longer show as mandatory since it has a default value
Changed the targetDate to be mandatory in investigation creation
=> [DO-1499]: UX review fixes

frontend/src/app/modules/shared/modules/relations/presentation/helper/d3.render.helper.ts
Fixed the direction of the arrows when collapsing a tree direction.
=> [DO-4769][patch] changed direction of the arrows

.github/workflows/pull-request_backend.yml, pom.xml, tx-backend/pom.xml, tx-coverage/pom.xml
Updated dependencies to avoid vulnerabilities
=> DO-4273: Updated dependencies to avoid vulnerabilities

tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/dashboard/mapper/DashboardResponseMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/dashboard/rest/DashboardController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/dashboard/model/Dashboard.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/dashboard/service/DashboardServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotificationStatus.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/repository/QualityNotificationRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertsRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/repository/InvestigationsRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/application/rest/DashboardControllerTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/domain/dashboard/service/DashboardServiceImplTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/DashboardControllerAuthorizationIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/DashboardControllerIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/AlertNotificationsSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/AssetsSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/InvestigationNotificationsSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/testdata/AlertTestDataFactory.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/testdata/InvestigationTestDataFactory.java, tx-models/src/main/java/assets/response/DashboardResponse.java
Merge into common branch for collection frontend and backend changes before merging into dev branch
=> [DO-4302][feature] Fix display of number of received quality investigations/ alerts in dashboard

frontend/src/app/modules/core/layout/layout/layout.component.html, frontend/src/app/modules/core/layout/layout/layout.component.scss
Made the header sticky and added a elevation shadow
=> [DO-4912] Sticky header

frontend/src/app/modules/shared/components/table/table.component.ts
Fixed wrong routing from dashboard to selected investigation/alert
=> [DO-5011]: Fix wrong routing from dashboard to selected investigation/alert

frontend/src/app/modules/shared/components/table-settings/table-settings.component.ts
Fixed table column settings drag and drop reordering
=> [DO-4870] Fix table column settings drag and drop reordering

frontend/src/app/modules/page/alerts/detail/alert-detail.component.ts, frontend/src/app/modules/page/investigations/detail/investigation-detail.component.ts, frontend/src/app/modules/shared/components/table/table.component.ts
Fixed issue where clicking on investigation/alert from dashboard routing to wrong item
=> [DO 5011] Fixed issue where clicking on investigation/alert from dashboard routing to wrong item

frontend/src/index.html
=> [DO-4998] Added user centrics

frontend/src/app/modules/page/alerts/detail/alert-detail.component.html, frontend/src/app/modules/page/alerts/presentation/alerts.component.html, frontend/src/app/modules/page/alerts/presentation/alerts.component.scss, frontend/src/app/modules/page/alerts/presentation/alerts.component.spec.ts, frontend/src/app/modules/page/alerts/presentation/alerts.component.ts, frontend/src/app/modules/page/investigations/detail/investigation-detail.component.html, frontend/src/app/modules/page/investigations/presentation/investigations.component.html, frontend/src/app/modules/page/investigations/presentation/investigations.component.scss, frontend/src/app/modules/page/investigations/presentation/investigations.component.spec.ts, frontend/src/app/modules/page/investigations/presentation/investigations.component.ts, frontend/src/app/modules/page/parts/presentation/relation/relation.component.html, frontend/src/app/modules/shared/components/request-notification/request-notification.base.html, frontend/src/app/modules/shared/components/request-notification/request-notification.base.scss, frontend/src/app/modules/shared/components/request-notification/request-notification.base.ts, frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.html, frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.scss, frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.ts, frontend/src/app/modules/shared/components/table-settings/table-settings.component.html, frontend/src/app/modules/shared/modules/modal/component/modal.component.html, frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.html, frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json, frontend/src/theme/base.scss
Implemented the creation of investigations and alerts from their respective subpages
Fixed issue in "Investigation for components"-tab where you you're unable to create investigations
UX review changes
=> [DO-5096] Investigation from subpage

cfx-frontend/src/app/modules/core/user/table-settings.service.ts, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, cfx-frontend/src/app/modules/shared/components/request-notification/request-notification.base.html, cfx-frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.ts, cfx-frontend/src/app/modules/shared/components/table-settings/table-settings.component.ts, cfx-frontend/src/app/modules/shared/components/table/table.component.ts, cfx-frontend/src/app/modules/shared/helper/filter-helper.ts, cfx-frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.ts
fix:[BA-635] Clicking outside of filter dialog shows close confirmation 
fix:[BA-634] Chips in alerts/investigation creation shows ids instead of names 
fix:[BA-632] Tablesettings on dashboard not working 
fix:[BA-633] Global search on request stepper not working
fix:[BA-64] Settings to local storage saved with username as key
[BA-635]: https://cofinity-x.atlassian.net/browse/BA-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BA-634]: https://cofinity-x.atlassian.net/browse/BA-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BA-632]: https://cofinity-x.atlassian.net/browse/BA-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BA-633]: …
=> [BA-633] Various frontend merge fixes

cfx-frontend/src/index.html
=> BA-96  TRX_Integrate Google Tag Manager & UserCentrics

cfx-frontend/src/app/modules/shared/components/table-settings/table-settings.component.html, cfx-frontend/src/app/modules/shared/components/table-settings/table-settings.component.ts
Fixed table settings button disappearing after table settings is closed
=> [BA-662]: Fixed table settings button disappearing after table settings is closed

cfx-frontend/src/app/modules/shared/components/table/table.component.ts
Fixed clicking on table row not redirecting to details page
=> [BA-631] Fix table row click details

cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.scss, cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table-config.utils.ts, cfx-frontend/src/app/modules/shared/components/parts-table/table-view-config.model.ts, cfx-frontend/src/app/modules/shared/components/table/table.component.ts, cfx-frontend/src/app/modules/shared/model/filter-config.ts
Fixed the following broken filters
https://cofinity-x.atlassian.net/browse/BA-625
https://cofinity-x.atlassian.net/browse/BA-624
https://cofinity-x.atlassian.net/browse/BA-623
=> [BA-687] fix table filter description

cfx-frontend/src/app/modules/page/dashboard/abstraction/dashboard.facade.ts
Fixed dashboard alerts showing investigations
=> fix:[BA-727] Fixed dashboard alerts showing investigations

cfx-frontend/src/app/modules/page/parts/presentation/own-parts/own-parts.component.ts, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, cfx-frontend/src/app/modules/shared/components/table/table.component.html, cfx-frontend/src/app/modules/shared/components/table/table.component.ts, cfx-frontend/src/app/modules/shared/components/table/tableSortingUtil.ts
Fixed multi sort indicators overlapping and multiplying weirdly
=> [BA-688] Fixed multi sort indicators overlapping and multiplying weirdly

cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.scss, cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts, cfx-frontend/src/assets/locales/de/common.json, cfx-frontend/src/assets/locales/en/common.json, cfx-frontend/src/theme/base.scss
Implementation of UX designs for multiselect autocomplete component
=> [BA-118] Style multiselect autocomplete component

cfx-frontend/src/app/modules/page/alerts/presentation/alerts.component.ts, cfx-frontend/src/app/modules/page/investigations/presentation/investigations.component.ts, cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.scss
Fixed Quality Investigations/Alerts resetting filters when sorting is also used
=> [BA-784] Fixed Quality Investigations/Alerts resetting filters when sorting is also used

cfx-frontend/src/app/modules/core/user/table-settings.service.ts, cfx-frontend/src/app/modules/core/user/user.service.ts, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, cfx-frontend/src/app/modules/shared/components/table-column-settings/table-column-settings.component.ts, cfx-frontend/src/app/modules/shared/components/table/table.component.ts
Fixed local storage issue when saving table columns settings
=> [BA-787] Fix local storage issue when saving table columns settings

cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts
Fixed paginator 'Show' not being translated
=> fix:[BA-700] Fixed paginator 'Show' not being translated

cfx-frontend/src/app/modules/shared/assembler/notification-action-helper.service.ts
Disabled Approve and Close functionality for User role and enforced Supervisor role functionality
=> [BA-695] Role feature updates

cfx-frontend/src/app/modules/core/layout/footer/footer.component.scss, cfx-frontend/src/app/modules/core/layout/header/header.component.scss, cfx-frontend/src/app/modules/core/layout/layout/layout.component.html, cfx-frontend/src/app/modules/core/layout/layout/layout.component.scss, cfx-frontend/src/app/modules/page/alerts/detail/alert-detail.component.html, cfx-frontend/src/app/modules/page/alerts/presentation/alerts.component.html, cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html, cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.scss, cfx-frontend/src/app/modules/page/investigations/detail/investigation-detail.component.html, cfx-frontend/src/app/modules/page/investigations/presentation/investigations.component.html, cfx-frontend/src/app/modules/page/other-parts/presentation/other-parts.component.html, cfx-frontend/src/app/modules/page/parts/presentation/parts.component.html, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.scss, cfx-frontend/src/app/modules/shared/components/request-notification/request-notification.base.scss, cfx-frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.scss, cfx-frontend/src/app/modules/shared/components/table-column-settings/table-column-settings.component.html, cfx-frontend/src/app/modules/shared/components/table-column-settings/table-column-settings.component.scss, cfx-frontend/src/app/modules/shared/components/table/table.component.scss, cfx-frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.html, cfx-frontend/src/assets/locales/de/common.json, cfx-frontend/src/assets/locales/en/common.json, cfx-frontend/src/assets/locales/en/page.about.json, cfx-frontend/src/theme/base.scss
Improved dialog responisiveness to browser size changes
Fixed grammar mistake in about page text
Changed "Reset all" to "Reset filters and sorting" in table settings
This also fixes: https://cofinity-x.atlassian.net/browse/BA-553
=> [BA-783] Improved dialog responisiveness to browser size changes

cfx-frontend/src/app/modules/shared/modules/notification/modal/cancel/cancel-notification-modal.component.html, cfx-frontend/src/app/modules/shared/modules/notification/modal/close/close-notification-modal.component.html, cfx-frontend/src/theme/base.scss
Fixed text-area error message overlapping formfield border
=> [BA-884] Fixed text-area error message overlapping formfield border

cfx-frontend/src/app/modules/core/layout/footer/footer.component.scss, cfx-frontend/src/app/modules/core/layout/header/header.component.scss, cfx-frontend/src/app/modules/core/layout/layout/layout.component.html, cfx-frontend/src/app/modules/core/layout/layout/layout.component.scss, cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html, cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.scss, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, cfx-frontend/src/app/modules/shared/components/parts-table/parts-table.component.scss, cfx-frontend/src/app/modules/shared/components/request-notification/request-stepper/request-stepper.component.scss, cfx-frontend/src/assets/locales/en/page.about.json, cfx-frontend/src/theme/base.scss
Made changes to the responsiveness to browser size required by UX review
=> [BA-783] UX Review changes for browser size responsiveness 

cfx-frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.ts, cfx-frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.spec.ts, cfx-frontend/src/app/modules/shared/helper/filter-helper.ts, cfx-frontend/src/app/modules/shared/service/parts.service.ts
Fixed the issue where the searchbar was no longer working for parts/sharedParts
=> [BA-935] Fixed search not working in parts/sharedParts

cfx-frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.html, cfx-frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.scss, cfx-frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.ts
Implemented indicator for toast/snackbar duration
=> feature:[BA-937] Implemented indicator for toast/snackbar duration

cfx-frontend/src/app/modules/shared/components/parts-table/parts-as-built-configuration.model.ts, cfx-frontend/src/app/modules/shared/modules/relations/core/relations.facade.spec.ts, cfx-frontend/src/app/modules/shared/modules/relations/core/relations.facade.ts, cfx-frontend/src/app/modules/shared/modules/relations/presentation/tree.component.ts, cfx-frontend/src/app/modules/shared/service/parts.service.ts
Fixed child part names missing for as planned in my parts
=> fix:[BA-584] Fixed child part names missing for as planned

cfx-frontend/src/app/modules/shared/modules/part-details/presentation/start-investigation/start-investigation.component.ts, cfx-frontend/src/app/modules/shared/service/parts.service.ts
Removed own parts in start investigation of components
=> fix:[BA-586] Remove own parts in start investigation of components

tx-backend/src/main/resources/db/migration/V22__merge_alert_and_notification_tables.sql
- Updated data migration script to fix null value
=> [chore] BA-986 Create data migration script

cfx-frontend/src/assets/locales/de/page.imprint.json, cfx-frontend/src/assets/locales/en/page.imprint.json
Fix of Imprint. See BA-1035 https://cofinity-x.atlassian.net/browse/BA-1035
=> [BA-1035][fix] fix imprint data
